name: Auto Merge on Label

on:
  pull_request:
    types: [labeled]
env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    if: ${{ github.event.label.name == 'merge-to-qa' }}
    name: Merge QA
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: perform merge
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git status
          git pull
          git checkout QA
          echo "checkout=> QA"
          git status
          # git checkout "$GITHUB_HEAD_REF"
          echo "checkout FEAT=> $GITHUB_HEAD_REF"
          git merge "$GITHUB_HEAD_REF" --no-edit
          git push
          git status

      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: merge-to-qa
